// Generated by CoffeeScript 1.6.3
(function() {
  var benny, pw;

  pw = new UserPassword("abc123");

  benny = new User('Benny', 'benny@wearezeta.com', 'abc123');

  Registration.init();

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
