// Generated by CoffeeScript 1.6.3
(function() {
  var email, property, pw;

  property = new Zeta.Registration.UserProperty("property");

  alert(property.value);

  pw = new Zeta.Registration.UserPassword("password");

  alert(pw.value);

  email = new Zeta.Registration.UserEmailAddress("email");

  alert(email.value);

}).call(this);

/*
//@ sourceMappingURL=debug.map
*/
