// Generated by CoffeeScript 1.6.3
(function() {
  var Registration;

  Registration = (function() {
    var host, url, user;
    host = 'https://armada-test.z-infra.com';
    url = {
      access: host + '/access',
      login: host + '/login',
      register: host + '/register'
    };
    user = new User("", "", "");
    return {
      init: function() {
        return $('#registration-form-name').on('blur', function() {
          user.name.value = $(this).val();
          console.log("Username: " + user.name.value + " | valid: " + (user.name.isValid()));
          if (!user.name.isValid()) {
            return alert("username invalid");
          }
        });
      },
      register: function(user) {
        if (user.hasValidRegistrationData) {
          return RequestHandler.postData(url.register, user.getRegistrationPayload(), function(data, textStatus, jqXHR) {
            alert(JSON.stringify(data));
            return function(data, textStatus, jqXHR) {
              return alert(JSON.stringify(data));
            };
          });
        }
      }
    };
  })();

}).call(this);

/*
//@ sourceMappingURL=Registration.map
*/
