// Generated by CoffeeScript 1.6.3
/*
  https://docs.z-infra.com/dev-device-api/latest/reference/users.html
*/


(function() {
  var User,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  User = (function() {
    function User(name, email, password) {
      this.getRegistrationPayload = __bind(this.getRegistrationPayload, this);
      this.name = new UserProperty(name);
      this.email = new UserEmailAddress(email);
      this.password = new UserPassword(password);
    }

    User.prototype.optional = {
      accent: [],
      picture: [],
      phone: "",
      phone_code: ""
    };

    User.prototype.getRegistrationPayload = function() {
      var key, payload;
      payload = {};
      for (key in this) {
        if (this[key] instanceof UserProperty && this[key].isValid()) {
          payload[key] = this[key].value;
        }
      }
      return JSON.stringify(payload);
    };

    User.prototype.hasValidRegistrationData = function() {
      if (this.name.isValid() && this.email.isValid() && this.password.isValid()) {
        return true;
      } else {
        return false;
      }
    };

    return User;

  })();

}).call(this);

/*
//@ sourceMappingURL=User.map
*/
